# This is given as a sample, you should probably create your own in production
version: '3'

services:
  bot:
    image: docker.pkg.github.com/lolpants/minesweeper-bot/minesweeper-bot
    build: '.'
    restart: always
    env_file:
      - .env
